name: plass
description: Plass Usuario

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 7.9.8+7.9.8

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  here_sdk:
    path: plugins/here_sdk

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  url_launcher: ^6.0.20
  flutter_launcher_icons: ^0.9.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  package_info_plus: ^1.4.0
  skeletons: ^0.0.3
  country_code_picker: ^2.0.2
  device_info_plus: ^3.2.2
  location: ^4.3.0
  pin_code_fields: ^7.3.0
  cached_network_image: ^3.2.0
  paginate_firestore: ^1.0.3
  intl: ^0.17.0
  badges: ^2.0.2
  firebase_messaging: ^11.2.11
  image_picker: ^0.8.4+11
  image_cropper: ^1.5.0
  firebase_storage: ^10.2.10
  bubble: ^1.2.1
  flutter_rating_bar: ^4.0.0
  connectivity_plus: ^2.3.0
  qr_code_scanner: ^0.7.0
  flutter_ringtone_player: ^3.2.0
  get_test: ^4.0.1
  fake_cloud_firestore: ^1.2.2
  firebase_auth_mocks: ^0.8.4
  enum_to_string: ^2.0.1
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/PLASS.png
    - assets/main/foreground-icon.png
    - assets/main/PlassLogo.png
    - assets/main/Artwork.png
    - assets/icons/sideMenu.png
    - assets/icons/HandUp.png
    - assets/icons/currentLocation.png
    - assets/icons/pickup.png
    - assets/icons/drop.png
    - assets/icons/cars/standar.png
    - assets/icons/cars/standar-min.png
    - assets/icons/cars/standar-min-ios.png
    - assets/icons/by-woman.png
    - assets/icons/camera.png
    - assets/icons/taxi.png
    - assets/icons/min.png
    - assets/icons/med.png
    - assets/icons/max.png
    - assets/3d/sedan.obj
    - assets/3d/plane.obj