// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh2qspiEQpLrAkVKt4155qVrLZgXt5tQo',
    appId: '1:129374392713:ios:cc09bb902a27b0fa4f1158',
    messagingSenderId: '129374392713',
    projectId: 'plass-282915',
    databaseURL: 'https://plass-282915.firebaseio.com',
    storageBucket: 'plass-282915.appspot.com',
    androidClientId: '129374392713-3sl9k32jhm4g49trnkkrf64kvmhdqn0i.apps.googleusercontent.com',
    iosClientId: '129374392713-tlk9ao9d6a3dc3rhhbqoubpm4q7osbl0.apps.googleusercontent.com',
    iosBundleId: 'app.plass.user',
  );
}
